version: '3.9'

services:
  slack-liker:
    build:
      context: ./app
    env_file: ./app/.env
    # environment:
    #   - SLACK_USER_TOKEN=${SLACK_USER_TOKEN}
    #   - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
    #   - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
    volumes:
      - ./app:/usr/src/app
    restart: always
